### ISSUE TITLE
Problem with comparison char with NO_AREA_SELECTION

### ISSUE THREAD

**Issue by volvofixthis** [moverest/wl-kbptr#11]
In Clang it is not valid to compare char with -1. I tried to set NO_AREA_SELECTION with 255 and it worked out.
![image](https://github.com/moverest/wl-kbptr/assets/8951380/c0974315-b8a4-428f-9bbb-4f37a7ae043a)

**Comment by moverest** [comment]
That's interesting. I assumed `char` was a signed and it does compile without error on my machine with Clang. It appears that that's not the case with all architectures. What architecture and system are you building this for?

A more resilient fix would probably be to use `int8_t` from `stdint.h` instead of the `char` type.

**Comment by moverest** [comment]
I've just pushed 8558547fd308b84732cbdc653dd131797effe0b3. Please tell me if this fixes the issue.

**Comment by volvofixthis** [comment]
I use Asahi linux on air m2. It is aarch64.
