### ISSUE TITLE
Cursor position not correct 

### ISSUE THREAD

**Issue by jheroy** [moverest/wl-kbptr#19]
![image](https://github.com/user-attachments/assets/ea148daf-249d-4af5-a81a-1ed490c83fe2)
As shown in the image, after pressing the Enter key, the cursor should appear at the red cross position, but it appears where the arrow points.

I use Hyprland:

Hyprland --version
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2

**Comment by moverest** [comment]
1. Which version of `wl-kbptr` are you using? Try with [`v0.2.2`](https://github.com/moverest/wl-kbptr/releases/tag/v0.2.2) to make sure this is not a issue that was fixed already (#7).
2. Do you have a panel at the top or bottom? If yes, which one?
3. Could you provide a screenshot of you whole screen when the grid is being displayed?

**Comment by moverest** [comment]
I tried to run your configuration and it wouldn't run on my machine without needing some troubleshooting so I tried Ags [`simple-bar` example](https://github.com/Aylur/ags/tree/main/example/simple-bar) and it did work as intended. Not sure why it's not working with your configuration.

![out](https://github.com/user-attachments/assets/6ae29081-0f48-4265-940a-fae7171c8567)

The issue here is that the overlay surface is not filling the whole screen. In order for wl-kbptr to display the overlay surface, it uses the [`wlr-layer-shell`](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) protocol with which it asks for the whole screen by setting the anchors to all the borders (top, right, left, bottom) and not requiring an exclusive zone. Then it assumes it got the whole screen as I have not found a way to check that it actually did. In you case this assumption turns out not to be true.

I can think of another program that does the same thing and it's [`slurp`](https://github.com/emersion/slurp). Could you try it and see if it takes the whole screen, i.e. it covers the bar as well? If it works I could look at what it does and might be able to do something about it.

**Comment by jheroy** [comment]
Yes, `slurp` can operate on the entire screen. In fact, the screenshot above was obtained using the command `grim -s 1 -g "$(slurp)" -|wl-copy`.

**Comment by moverest** [comment]
Does 6482eed7dab0ecfc482f96b5b1ebcbac71934d19 changes anything for you?

**Comment by jheroy** [comment]
Yes, the above modification works as expected.

**Comment by moverest** [comment]
Great. I've added the patched and created a new release with it ([`v0.2.3`](https://github.com/moverest/wl-kbptr/releases/tag/v0.2.3)).
